torchrun \
  --nproc_per_node=1 \
  train.py \
  --hf_model_token "" \
  --hf_data_token "" \
  --hub_token "" \
  --output_dir "/workspace/result/modern_bert" \
  --model_name_or_path "x2bee/KoModernBERT-base-mlm-v02" \
  --model_subfolder "last-checkpoint" \
  --train_data "x2bee/cc-100-korean" \
  --train_data_dir "chunk_02" \
  --train_data_split 'train' \
  --train_test_split_ratio 0.05 \
  --report_to "mlflow" \
  --overwrite_output_dir True \
  --save_strategy "steps" \
  --save_steps 1500 \
  --eval_strategy "steps" \
  --eval_steps 1000 \
  --save_total_limit 1 \
  --push_to_hub True \
  --hub_model_id "x2bee/KoModernBERT-base-mlm-v03_ckp00" \
  --hub_strategy "checkpoint" \
  --model_commit_msg "cc-100_0-1" \
  --logging_dir "/workspace/result/logs" \
  --logging_steps 50 \
  --max_grad_norm 0.8 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 8 \
  --gradient_accumulation_steps 8 \
  --learning_rate 1e-6 \
  --num_train_epochs 1 \
  --dataloader_drop_last True \
  --warmup_ratio 0.1 \
  --max_len 512 \
  --eval_step 5000 \
  --weight_decay 0.01 \
  --do_train True \
  --do_eval True \
  --save_only_model False \
  --flash_attn True