torchrun \
  --nproc_per_node=1 \
  train.py \
  --hf_model_token "" \
  --hf_data_token "" \
  --hub_token "" \
  --output_dir "/workspace/result/sts_train_test" \
  --overwrite_output_dir True \
  --push_to_hub True \
  --hub_model_id "x2bee/sts_nli_test_01" \
  --hub_strategy "checkpoint" \
  --report_to "mlflow" \
  --max_grad_norm 1 \
  --model_name_or_path "x2bee/KoModernBERT-base-mlm-v02-ckp02" \
  --train_data "x2bee/Korean_NLI_dataset" \
  --train_data_dir "pair-score" \
  --train_data_split 'train' \
  --test_data "CocoRoF/sts_dev" \
  --train_test_split_ratio 0 \
  --learning_rate 1e-4 \
  --logging_steps 100 \
  --save_strategy "steps" \
  --save_steps 1500 \
  --eval_strategy "steps" \
  --eval_steps 1000 \
  --num_train_epochs 2 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 8 \
  --gradient_accumulation_steps 16 \
  --dataloader_drop_last \
  --warmup_ratio 0.1 \
  --max_len 512 \
  --eval_step 5000 \
  --weight_decay 0.01 \
  --flash_attn False