torchrun \
  --nproc_per_node=1 \
  train.py \
  --output_dir "/workspace/result/ce_train_test" \
  --model_name_or_path "x2bee/KoModernBERT-base-mlm-v01-ckp02" \
  --train_data "CocoRoF/msmacro_triplet_ko" \
  --data_dir "triplet_ko" \
  --hf_model_token "" \
  --hf_data_token "" \
  --hub_token "" \
  --learning_rate 2e-4 \
  --num_train_epochs 1 \
  --per_device_train_batch_size 4 \
  --gradient_accumulation_steps 32 \
  --dataloader_drop_last \
  --warmup_ratio 0.1 \
  --train_group_size 3 \
  --max_len 512 \
  --eval_step 5000 \
  --weight_decay 0.01 \
  --flash_attn False